name: Backend tests

on:
  push:
    branches: [ main ]
    paths:
      - 'mymoni-backend/**'
  pull_request:
    paths:
      - 'mymoni-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        working-directory: mymoni-backend
        run: mvn --batch-mode --update-snapshots package
